### ISSUE TITLE
Before Moving to Express org

### ISSUE THREAD

**Issue by jonchurch** [bjohansebas/codemod#12]
Hey @bjohansebas and @kjugi this came up in the recent TC meeting, @kjugi was there before we kicked him out to talk security

We can move this into express org if yall are open to it and when you're ready.

At a minimum the project should have:

- [ ] Readme file, explaining how to use the codemods
- [ ] License file

**Comment by kjugi** [comment]
Thanks for the issue. I wanted to create one to propose checking our codemode in some projects just to test it out. Do we want to treat it as another point to our minimum plan?

Example repos sent during the meeting:
- https://github.com/UlisesGascon/simple-api/tree/main/src
- https://github.com/wesbos/Learn-Node/tree/master/stepped-solutions/45%20-%20Finished%20App

**Comment by wesleytodd** [comment]
We also need the code of conduct

**Comment by bjohansebas** [comment]
>We also need the code of conduct

The code of conduct should be inherited from the organization's .github.
